name: masarat
description: "Masarat app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI packages
  cached_network_image: ^3.4.1
  custom_loading: ^1.0.3
  dotlottie_loader: ^0.0.5
  dropdown_button2: ^3.0.0-beta.20
  flutter_blurhash: ^0.8.2
  flutter_screenutil: ^5.9.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  lottie: ^3.3.1
  oktoast: ^3.4.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.1
  qr_flutter: ^4.1.0
  animated_splash_screen: ^1.3.0

  # State management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.4
  
  # Network & API
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  flutter_inappwebview: 5.7.2+3
  http: ^1.1.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  webview_flutter: 4.2.2
  webview_flutter_android: 3.9.3
  webview_flutter_wkwebview: 3.7.3
  youtube_player_flutter: ^8.1.2
  
  # Local storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  
  # DI
  get_it: ^8.0.3
  
  # Localization
  easy_localization: ^3.0.7+1
  localization:
    path: ./localization
  
  # Maps & Location
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  country_picker: ^2.0.25
  
  # Environment config
  flutter_dotenv: ^5.1.0
  
  # Utility packages
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  logger: ^2.5.0
  path_provider: ^2.0.11
  path: ^1.8.3
  file_picker: ^8.0.7
  go_router: ^15.1.2

  # Other functionality
  infinite_scroll_pagination: ^5.0.0
  share_plus: ^10.1.4
  
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_flavor: ^3.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  retrofit_generator: ^9.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.otf