name: masarat
description: Masarat app
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  textfield_tags: 3.0.1
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  country_picker: ^2.0.25
  custom_loading: ^1.0.3
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  dropdown_button2: ^3.0.0-beta.20
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_blurhash: ^0.8.2
  flutter_dotenv: ^5.1.0
  # Replaced flutter_inappwebview with webview_flutter (already included below)
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geolocator: ^11.0.0
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_maps_flutter: ^2.6.0
  http: ^1.1.0
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  localization:
    path: ./localization
  logger: ^2.5.0
  lottie: ^3.3.1
  dotlottie_loader: ^0.0.5
  oktoast: ^3.4.0
  path: ^1.8.3
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.4
  qr_flutter: ^4.1.0
  retrofit: ^4.4.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: 4.2.2
  webview_flutter_android: 3.9.3
  webview_flutter_wkwebview: 3.7.3
  easy_localization_loader: ^2.0.2
  file_picker: ^8.1.4
  http_parser: ^4.1.2
  # youtube_player_flutter: ^8.1.2 (commented out due to dependency on flutter_inappwebview)
  video_player: ^2.8.1
  chewie: ^1.7.5
  flutter_image_compress: ^2.4.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_flavor: ^3.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  retrofit_generator: ^9.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.otf