name: masarat
description: Masarat app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dropdown_button2: ^3.0.0-beta.20
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_blurhash: ^0.8.2
  flutter_inappwebview: 5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.16
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^14.6.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  localization:
    path: ./localization
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_flavor: ^3.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.otf
