// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        i18n = _assets_i18n_dart._(brightness: brightness),
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness),
        launcher_icon = _assets_launcher_icon_dart._(brightness: brightness),
        lottie = _assets_lottie_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_i18n_dart i18n;
  final _assets_icons_dart icons;
  final _assets_images_dart images;
  final _assets_launcher_icon_dart launcher_icon;
  final _assets_lottie_dart lottie;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Montserrat_otf = 'assets/fonts/Montserrat.otf';
}

class _assets_i18n_dart {
  final Brightness _brightness;

  _assets_i18n_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final ar_yaml = 'assets/i18n/ar.yaml';
  final en_yaml = 'assets/i18n/en.yaml';
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final app_icon_with_text_svg = 'assets/icons/app_icon_with_text.svg';
  final app_icon_with_text_green_svg = 'assets/icons/app_icon_with_text_green.svg';
  final drawer_icon_svg = 'assets/icons/drawer_icon.svg';
  final edit_icon_svg = 'assets/icons/edit_icon.svg';
  final icon_person_svg = 'assets/icons/icon_person.svg';
  final menu_icon_svg = 'assets/icons/menu_icon.svg';
  final star_beginner_svg = 'assets/icons/star_beginner.svg';
  final three_star_svg = 'assets/icons/three_star.svg';
  final two_star_svg = 'assets/icons/two_star.svg';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final slide_png = 'assets/images/slide.png';
}

class _assets_launcher_icon_dart {
  final Brightness _brightness;

  _assets_launcher_icon_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final launcher_icon_png = 'assets/launcher_icon/launcher_icon.png';
  final launcher_icon_svg = 'assets/launcher_icon/launcher_icon.svg';
}

class _assets_lottie_dart {
  final Brightness _brightness;

  _assets_lottie_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final loading_lottie = 'assets/lottie/loading.lottie';
}
